# -*- coding: utf-8 -*-
"""ListaPerro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10tIT0-QezMorZix8Nn1fkqM2Uumgcc1m
"""

Perro = [13,  "Puppy",  "12/12/2012" , "Macho", 123]
print (Perro)

Perro = [13,  "Puppy",  "13/12/2012" , "Macho", 28957346]
print (Perro)